// web/src/__tests__/data-testid-coverage.test.tsx
/**
 * W3.4 guard: every interactive element rendered by representative pages must
 * carry a kebab-case data-testid="<feature>-<area>-<action>". Pages mounted:
 *  - <ComputeTab>
 *  - <SelectorTab projectId="local" />
 *  - <ClusteringTab projectId="local" />
 *  - <ExplorerTab projectId="local" />
 *  - <Sidebar />
 *
 * Selector: button, input, select, a, [role="button"]. The set excludes inputs
 * that are explicitly hidden (type=hidden) and links generated by ReactRouter
 * <Navigate>.
 */
import React from 'react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'
import { Toaster } from 'sonner'
import { ComputeTab } from '@/pages/ComputeTab'
import { SelectorTab } from '@/pages/SelectorTab'
import { ClusteringTab } from '@/pages/ClusteringTab'
import { ExplorerTab } from '@/pages/ExplorerTab'
import { Sidebar } from '@/components/Sidebar'

vi.mock('react-plotly.js', () => ({ default: () => <div data-testid="plotly-mock" /> }))
vi.mock('openseadragon', () => ({
  default: vi.fn(() => ({
    open: vi.fn(),
    destroy: vi.fn(),
    addOverlay: vi.fn(),
    removeOverlay: vi.fn(),
    clearOverlays: vi.fn(),
    addHandler: vi.fn(),
    world: { getItemCount: () => 0, getItemAt: () => ({ setOpacity: vi.fn() }) },
    viewport: {
      viewerElementToViewportCoordinates: () => ({ x: 0, y: 0 }),
      viewportToImageCoordinates: () => ({ x: 0, y: 0 }),
    },
    element: document.createElement('div'),
  })),
}))

const KEBAB = /^[a-z][a-z0-9]*(-[a-z0-9]+)+$/

const SELECTOR = ['button', 'input', 'select', 'a', '[role="button"]'].join(',')

function wrap(ui: React.ReactNode) {
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: 0 } } })
  return (
    <QueryClientProvider client={qc}>
      <MemoryRouter>
        <Toaster />
        {ui}
      </MemoryRouter>
    </QueryClientProvider>
  )
}

interface PageCase {
  name: string
  ui: React.ReactNode
}

const PAGES: PageCase[] = [
  { name: 'ComputeTab', ui: <ComputeTab /> },
  { name: 'SelectorTab', ui: <SelectorTab projectId="local" scanId={11} /> },
  { name: 'ClusteringTab', ui: <ClusteringTab projectId="local" scanId={11} /> },
  { name: 'ExplorerTab', ui: <ExplorerTab projectId="local" scanId={11} /> },
  { name: 'Sidebar', ui: <Sidebar /> },
]

describe.each(PAGES)('data-testid coverage on $name', ({ ui }) => {
  beforeEach(() => {
    vi.unstubAllGlobals()
    vi.stubGlobal(
      'fetch',
      vi.fn(
        () =>
          new Promise(() => {
            /* hold queries in loading state */
          })
      )
    )
  })

  it('every interactive element has a kebab-case data-testid', () => {
    const { container } = render(wrap(ui))
    const interactive = Array.from(container.querySelectorAll(SELECTOR)).filter((el) => {
      // skip hidden inputs
      if (el instanceof HTMLInputElement && el.type === 'hidden') return false
      return true
    })
    const offenders = interactive
      .map((el) => ({
        tag: el.tagName.toLowerCase(),
        testid: el.getAttribute('data-testid'),
        outerHTML: el.outerHTML.slice(0, 200),
      }))
      .filter((o) => !o.testid || !KEBAB.test(o.testid))
    if (offenders.length > 0) {
      // eslint-disable-next-line no-console
      console.error('data-testid offenders:', offenders)
    }
    expect(offenders).toEqual([])
  })
})
